### PR TITLE
Changed sidebar icons

### PR DESCRIPTION
**Pull request by Jixiee**
Changed the icons of the sidebar

### CODE REVIEW

**Comment by bhanuvrat** [comment]
the phoenix scaffold provides a helper function for using hero icons.
can you try to use it 

https://github.com/essentiasoftserv/vachan/blob/main/lib/vachan_web/components/core_components.ex#L667 ?

**Comment by Jixiee** [comment]
> the phoenix scaffold provides a helper function for using hero icons. can you try to use it
> 
> https://github.com/essentiasoftserv/vachan/blob/main/lib/vachan_web/components/core_components.ex#L667 ?

Sure, I will try it out.

**Comment by Jixiee** [comment]
> the phoenix scaffold provides a helper function for using hero icons. can you try to use it
> 
> https://github.com/essentiasoftserv/vachan/blob/main/lib/vachan_web/components/core_components.ex#L667 ?

Made the changes you asked for could you please review it again.

**Comment by bhanuvrat** [comment]
👍🏼

**Comment by bhanuvrat** [comment]
lgtm

**Pull request merged**
